// SPDX-License-Identifier: MIT
#include <stdint.h>
#include <stdio.h>

#define CRC32_POLY 0x04C11DB7
static uint32_t crc32table[256];

/**
 * init_crc32table - Initialize the CRC32 lookup table according to RP2040
 * specs.
 *
 * See RP2040 Datasheet, Rev 1.4, Section 2.8.1.3.1 for details:
 * https://datasheets.raspberrypi.com/rp2040/rp2040-datasheet.pdf
 */
static void init_crc32table(void) {
  unsigned i, j;
  uint32_t crc = 0x80000000;

  crc32table[0] = 0;
  for (i = 1; i < 256; i <<= 1) {
    crc = (crc << 1) ^ ((crc & 0x80000000) ? CRC32_POLY : 0);
    /* crc represents the crc32table value for 'i'.
     * Use this to populate entries for i + j where j < i.
     */
    for (j = 0; j < i; j++) {
      crc32table[i + j] = crc ^ crc32table[j];
    }
  }
}

/**
 * output_crc32table - Output the generated CRC32 lookup table as C source code.
 *
 * The output includes a macro for CRC32 size and the
 * initialized crc32table array definition.
 */
static void output_crc32table(void) {
  printf("// Code generated by gen_crc32table.c, do not modify.\n\n");

  printf("#define CRC32_SIZE 4\n\n");
  printf("static const unsigned int crc32table[256] = {\n");
  for (unsigned i = 0; i < 256; i++) {
    printf("    %u,\n", crc32table[i]);
  }
  printf("};\n");
}

int main(int argc, char **argv) {
  (void)argc; /* unused */
  (void)argv; /* unused */

  init_crc32table();
  output_crc32table();

  return 0;
}
